#!/bin/bash

for data_name in A_final_rouge12L_aug_mix_1_filtering_true_30epoch A_final_rouge12L_aug_pair_1_filtering_false_30epoch A_final_rouge12L_aug_pair_2_filtering_true_30epoch A_final_rouge12L_aug_pair_3_filtering_true_30epoch A_final_rougeL_aug_mix_1_filtering_true_30epoch A_final_rougeL_aug_pair_1_filtering_false_30epoch A_final_rougeL_aug_pair_2_filtering_true_30epoch A_final_rougeL_aug_pair_3_filtering_true_30epoch A_final_rougeL_ori_mix_1_filtering_true_30epoch
do
python3 calculate_scores.py -data_name $data_name 
done